# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#
# Publish PyPI and NPM artifacts
#
name: Publish

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "contrib/**"
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/publish.yaml"
  push:
    paths-ignore:
      - "docs/**"
      - "contrib/**"
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/publish.yaml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.13"

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24"
          package-manager-cache: false
          registry-url: https://registry.npmjs.org

      - name: Update root build packages
        run: |
          pip install --upgrade build pip

      - name: Build dist
        run: |
          pyproject-build
          cd dist && sha256sum * | tee SHA256SUMS

      - name: Check dist sizes
        run: |
          set -eux
          ls -lathr dist
          [[ $(find dist -type f -size +200k) ]] && exit 1 || echo ok

      - name: Javascript package
        run: |
          mkdir jsdist
          cd jsdist
          npm pack ../labextension
          sha256sum * | tee SHA256SUMS

      - name: Upload Python artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: dist-${{ github.run_attempt }}
          path: dist
          if-no-files-found: error

      - name: Upload Javascript artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: jsdist-${{ github.run_attempt }}
          path: jsdist
          if-no-files-found: error

  # https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
  publish-pypi:
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    environment:
      name: release
    needs:
      - build
    permissions:
      id-token: write

    steps:
      - name: Download artifacts from build
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: dist-${{ github.run_attempt }}
          path: dist

      # The PyPI publishing action will try to publish this checksum file as if
      # it was a Python package if it remains in dist, so we clean it up first.
      - name: Cleanup SHA256SUMS
        run: |
          cat dist/SHA256SUMS
          rm dist/SHA256SUMS

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # release/v1

  # https://docs.github.com/en/actions/language-and-framework-guides/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
  publish-npm:
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    environment:
      name: release
    permissions:
      id-token: write

    steps:
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24"
          package-manager-cache: false
          registry-url: https://registry.npmjs.org

      - name: Download artifacts from build
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: jsdist-${{ github.run_attempt }}
          path: jsdist

      - run: |
          npm publish --dry-run --tag test ./jsdist/jupyterhub-jupyter-server-proxy-*.tgz

      - run: |
          npm publish ./jsdist/jupyterhub-jupyter-server-proxy-*.tgz
