# This workflow will install Python dependencies, run tests with several versions of Python and OS.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        experimental: [false]
        python-version: [3.5, 3.6]
        include:
          - os: windows-latest
          - python-version: 3.6
          - experimental: true
        exclude:
          - os: windows-latest
            python-version: 3.5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install .
          pip3 install pytest
        shell: bash
      - run: mkdir ./output
        shell: bash
      - name: Start Jupyter notebook
        run: jupyter-notebook --config=./tests/resources/jupyter_server_config.py &> ./output/log.txt &
        shell: bash
        env:
          JUPYTER_TOKEN: secret
      - name: Run tests
        shell: bash
        run: |
          sleep 20
          pytest
      - name: Stop Jupyter notebook
        run: jupyter-notebook stop 8888
        shell: bash
      - name: Save jupyter output log
        uses: actions/upload-artifact@v1
        with:
          name: jupyter-log
          path: ./output
